_target_: src.model.trancenet.SubtractCNN
height: 120
width: 160
rnn: GRU
teacher_forcing: true
c_pair_embed: 8
max_step: 4
c_hidden: [128]
cnn_c_kernels: [16, 32, 64, 64]
cnn_s_kernels: [5, 3, 3, 3]
fc_img_en: [128]
fc_fusion: [128]
